#SPDX-License-Identifier: MIT-0
---
# vars file for docker_engine

docker_apt_key_url: https://download.docker.com/linux/ubuntu/gpg
docker_apt_key_path: /usr/share/keyrings/docker-archive-keyring.gpg
docker_apt_repo: "deb [arch={{ ansible_architecture }} signed-by={{ docker_apt_key_path }}] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
docker_gpg_checksum: "sha256:d8985c490a0201d9f67645f8f847e7d057a7d4d732857f13962b8a7b9dd4b4a1"

