apiVersion: v1
kind: Service
metadata:
  name: datadash-frontend
  namespace: datadash
  labels:
    app: datadash-frontend
spec:
  selector:
    app: datadash-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
