#SPDX-License-Identifier: MIT-0
galaxy_info:
  author: erkdk
  description: "Ensures consistent hostname resolution via /etc/hosts."
  company: dataDash-devsecops
  license: MIT
  min_ansible_version: 2.1

